Repository nimblehq/gin-templates, pull requests merged in 2021-07, with the labels that each got.

#61 Refactor test to receive input as a parameter
  .github/workflows/test.yml
  Makefile
  README.md
  cmd/cmd_suite_test.go
  cmd/create_test.go
  tests/path.go
  tests/template.go
Labels: type : chore

#64 Refactor go cookiecutter
  tests/cookiecutter.go
  tests/template.go
Labels: type : chore

#53 Add logrus add-on
  cmd/create_test.go
  cookiecutter.json
  hooks/post_gen_project.py
  tests/cookiecutter.go
  {{cookiecutter.app_name}}/bootstrap/config.go
  {{cookiecutter.app_name}}/bootstrap/database.go
  {{cookiecutter.app_name}}/cmd/api/main.go
  {{cookiecutter.app_name}}/go.mod
  {{cookiecutter.app_name}}/go.sum
  {{cookiecutter.app_name}}/helpers/log/log.go
  {{cookiecutter.app_name}}/test/test.go
Labels: type : feature

#55 Add Heroku add-on
  cmd/create_test.go
  cookiecutter.json
  hooks/post_gen_project.py
  tests/cookiecutter.go
  {{cookiecutter.app_name}}/.gitignore
  {{cookiecutter.app_name}}/README.md
  {{cookiecutter.app_name}}/deploy/heroku/config.tf
  {{cookiecutter.app_name}}/deploy/heroku/main.tf
  {{cookiecutter.app_name}}/deploy/heroku/terraform.tfvars.sample
  {{cookiecutter.app_name}}/deploy/heroku/variables.tf
Labels: type : feature

#62 [50] Add web variant
  .gitignore
  cmd/create_test.go
  cookiecutter.json
  hooks/post_gen_project.py
  hooks/pre_gen_project.py
  tests/cookiecutter.go
  {{cookiecutter.app_name}}/.eslintrc.json
  {{cookiecutter.app_name}}/.gitignore
  {{cookiecutter.app_name}}/.npmrc
  {{cookiecutter.app_name}}/Makefile
  {{cookiecutter.app_name}}/Procfile.dev
  {{cookiecutter.app_name}}/README.md
  {{cookiecutter.app_name}}/bootstrap/config.go
  {{cookiecutter.app_name}}/bootstrap/database.go
  {{cookiecutter.app_name}}/bootstrap/router.go
  {{cookiecutter.app_name}}/lib/web/assets/images/logo.svg
  {{cookiecutter.app_name}}/lib/web/assets/javascripts/application.ts
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/_variables.scss
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/application.scss
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/base/.keep
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/components/.keep
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/functions/_sizing.scss
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/layouts/.keep
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/mixins/.keep
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/screens/.keep
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/vendors/.keep
  {{cookiecutter.app_name}}/lib/web/controllers/base.go
  {{cookiecutter.app_name}}/lib/web/controllers/home.go
  {{cookiecutter.app_name}}/lib/web/routers/router.go
  {{cookiecutter.app_name}}/lib/web/views/home/index.html
  {{cookiecutter.app_name}}/lib/web/views/layouts/application.html
  {{cookiecutter.app_name}}/lib/web/views/partials/_app_header.html
  {{cookiecutter.app_name}}/package.json
  {{cookiecutter.app_name}}/postcss.config.js
  {{cookiecutter.app_name}}/snowpack.config.js
  {{cookiecutter.app_name}}/tsconfig.json
Labels: @2.0.0, priority: normal, type : feature

#65 #56 Add Bootstrap addons
  cmd/create_test.go
  cookiecutter.json
  hooks/post_gen_project.py
  hooks/pre_gen_project.py
  tests/cookiecutter.go
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/application.scss
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/vendors/bootstrap/index.scss
  {{cookiecutter.app_name}}/package.json
Labels: @2.0.0, priority: normal, type : feature

#67 #59 Add Tailwind Add-on
  cmd/create_test.go
  cookiecutter.json
  hooks/post_gen_project.py
  hooks/pre_gen_project.py
  tests/cookiecutter.go
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/application.scss
  {{cookiecutter.app_name}}/lib/web/assets/stylesheets/vendors/tailwind/index.scss
  {{cookiecutter.app_name}}/package.json
  {{cookiecutter.app_name}}/postcss.config.js
  {{cookiecutter.app_name}}/tailwind.config.js
Labels: @2.0.0, priority: normal, type : feature
